name: CI/CD DevSecOps Pipeline

on: [push]

jobs:
  # --- GIAI ĐOẠN 3: BUILD & SECURITY SCAN ---
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. Secret Scanning (TruffleHog)
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@master
        
      # 2. Dependency Scanning (Snyk)
      - name: Snyk Monitor
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      # 3. Build Docker & Trivy Scan
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest'
          format: 'table'
          exit-code: '1' # Fail nếu lỗi Critical
          severity: 'CRITICAL,HIGH'

      # 4. Push to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest

  # --- GIAI ĐOẠN 4: DEPLOY & DAST ---
  deploy-and-dast:
    needs: build-and-scan # Chỉ chạy khi bước trên thành công
    runs-on: ubuntu-latest
    steps:
      # 1. Deploy lên EC2 qua SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest
            docker stop my-app || true
            docker rm my-app || true
            # Chạy map port 80 của server vào 5000 của container
            docker run -d --name my-app -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest

      # 2. DAST Scan (OWASP ZAP) - Tấn công thử website vừa deploy
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://${{ secrets.EC2_HOST }}/'
